language: go
# Does nothing when building on terranodo/tegola, but makes builds work cleanly on forks.
go_import_path: github.com/terranodo/tegola

go:
  - 1.9.x
  - 1.8.x
  - 1.7.x

env:
  global:
  # Secure DOCKER_USER & DOCKER_PASSWORD
    - secure: "FyqhU6uxoXdod4i4RlSWE+bvvG0BmctIhGE+oWOlO6kvpOLO9UwDhCkQdq7XQipzR0w5Na7jH4DwZVpksRVJMqj12jS0aA5+ABXK0uskIukJEPjmpbzfqZENPSY7iIeT8bZCO5o/0a3a8dcGVlnCDtC2SHva/V6jhujhH2BAjzwWYhkIdAF8bPc2zW5TqqPXAft8ePFsApUba0QXXdnrEIvSbmaH6s3DCSQxR5QjccgCZyb2uNMLTffyLeRPp5cdDW+ps2ew5IhShMFhdcefhVYmIoh1fd9++tCuI/rSemg6VYPF5SF5hj3kZeKoG/HhFWUri0DbjJXVQ5L3Vgj7AxjFHITtIQ5tPDU6ewKDSw7kXjTZflL0zRCCPx0foaZSdyADysj2tC3wclj9+VH7eZMjpQ0p/BuiA9YT5VA9a6MvPSyz8YFXkRBljsDKz/HNRoGkSPiXAUgcGNxB9Qg3s2BRWh/s35NpjYOmaowRw1bCOrZtWtMhLsV8dNRjZhzgwfRgMAJq7bBP94Ov6qyP6xmYF/H8c0fubw+G2i7bXQUgM1BQXqfll8R/24tKAvdAZvI7YpYXfKrU2bf59U3tNEHkew9CansmRWVjb6QIyna0nlTWTAQ5ElQDV1/1f1a4aqV6JIoyfpTh9xFsl5vMIXktOANLeT/Bc+I5SvX+aAo="
    - RUN_POSTGIS_TESTS=yes
    - PGHOST="localhost"
    - PGPORT=5432
    - PGDATABASE="tegola"
    - PGUSER="postgres"

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-9.4-postgis-2.3

install:
  - bash ci/build_bindata.sh
  - bash ci/config_postgis.sh

before_deploy:
  - go get github.com/mitchellh/gox
  - pushd cmd/tegola/
  - gox -os='linux' -arch='386' -ldflags "-w -X main.Version=$TRAVIS_TAG" -output "{{.Dir}}_{{.OS}}_{{.Arch}}"
  - popd
  - docker build -f docker/Dockerfile -t jivanamara/tegola:alpha_01 .
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push jivanamara/tegola:alpha_01

deploy:
  provider: releases
  api_key:
    secure: "iGPDK26BOmZQr6AOmOWmFdVIlj1Dq7MeRUdWq35tD3b6HoUr+0kVJ4tZzHsy/y24qvfOTqn6xutff10CssT+cmeqBtVFOoyG907Qsr3gGFefc4BFPBUSh6rx46ex3PMFz5gSAIqQ5joYeT2dWH5FLMTZ8GpUQ04SKQUWQtctxN/7uDnFHMB5zslHky2gz9Fwa+bwJj7hd6VeTqvzZ4Hn9Yjct/U/cyvyhBmlo+hf+iBq0YQMEYAQLt49PAzZK5yvE/Xl7IMWmdCOmEx8hSZ4jSjiFlAnW22E2p086Gp20k0nDxqRjcFCt3ZDNom/S2gSVFeybS/lRBvPzCZFU+r3AGyeT60emAdbzVLxRz727ZBZf6+WYM2La2vUFzd9vqSmyOGItKl/Eyvutv9bxXpy49Yo+DQ6faeCiwDurEygFN4h87W3KOwBV7QfD1WhMNeJi5Vkyp0C1WZaMiS7oDEYTIeERx+DPAQNkc90Btz3Bi62GrLRSi/TPFAzrA5/CQqYjGfqfvYTrkGO2y3Se/C2k/c8Y1Yt/cWjmj9a5YVSlJGAuTkaGTCGG0EfVAN2UULWD1zuN7DeFuEiaPqK3DBGIW7GyTYmOxG17ZxhNG2YLrytMhCJfJLIhK6ldQrtsxT6Ar7RZZ7/yyWlObw0fD+Mm8qPcPpps6wmk3RHgYagLzg="
  file:
  #  - "tegola_darwin_386"
    - "tegola_linux_386"
  #  - "tegola_netbsd_arm"
  #  - "tegola_darwin_amd64"
  #  - "tegola_linux_amd64"
  #  - "tegola_openbsd_386"
  #  - "tegola_freebsd_386"
  #  - "tegola_linux_arm"
  #  - "tegola_openbsd_amd64"
  #  - "tegola_freebsd_amd64"
  #  - "tegola_netbsd_386"
  #  - "tegola_windows_386.exe"
  #  - "tegola_freebsd_arm"
  #  - "tegola_netbsd_amd64"
  #  - "tegola_windows_amd64.exe"
  skip_cleanup: true
  on:
    branch: issue-245_Add_docker_to_travis
#    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.9\.[0-9]+$

notifications:
  email:
    on_success: never
  slack:
    secure: TzRnZdJ1dhQJg9nby2oJ6qFj9Bl20VJ2aJXmXwADsj2ck/UGsFWpYNnqZVWvZomCZEJinFpA/h2TG1odEzg1BpCT0+rLIGQDAhIMVuici+nIs+DyPQmL2owG1LZ6/hzX09Y1mIZci0nmnI1wousfM8WDPRq5NSOsBeAMlixGR4g4lF8cp/R0B6CtcewtQx4RicdPJtopHDwXm5KI1/7euFcJwu15FWwWoUp6mOw+r44T1Md+qbqDKBbLSy+YvMkPcxI7HeECa7OP9OjkeUfU0BoMP6qqo9QTVX5v6lOHxA+FhueyyPrSTtNV377tilDy88kytqu6w8gcrxZOddj7nFbv6ErjfVaMfeepzk/HH2bzlLevvL+ukeJKrBNdmPuDRU3BqG5ygrdGAQUNpM7VSXLDcGrM2+ocVn/HO1NyXWwpejq7Gq0HWhNkYPHG5c7+khkQkRGJtg0wp9R3qXDAcRHLR+CHh89g5Blz4Wo6R/Q48MLJycbH/W56zsoe0xQ5Ww2eti16uSFE4kkiPt99uewWkPSfEZn4pyk+xCwDxgNDNu/BaV+Mjm4JTL1GjWalto+NLK7NsEg+6sEYok0CHkUb8MQV++r1KVfIaxC3zVuojIiOSB9/+JPtPd9w2iuVOlz0rrbXfKkkSf5wcmOguqk3aAfAgmcjAV9p1kI9pSc=